--
-- PostgreSQL database dump
--

\restrict MbqN0KD6WVjTDYps8aYZ8SUBplApPJcRSE2ejFXYtTYPorkEEb5s0BYnEwds7hn

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2025-12-12 16:33:00

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 24587)
-- Name: books; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.books (
    id bigint NOT NULL,
    date_added timestamp(6) without time zone,
    description character varying(255),
    title character varying(255) NOT NULL,
    author character varying(255),
    genre character varying(255),
    isbn character varying(255),
    publication_year integer
);


ALTER TABLE public.books OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 24586)
-- Name: books_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.books ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.books_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 24597)
-- Name: movies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.movies (
    id bigint NOT NULL,
    date_added timestamp(6) without time zone,
    description character varying(255),
    title character varying(255) NOT NULL,
    director character varying(255),
    duration_minutes integer,
    imdb_score double precision
);


ALTER TABLE public.movies OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 24596)
-- Name: movies_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.movies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5013 (class 0 OID 24587)
-- Dependencies: 220
-- Data for Name: books; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.books (id, date_added, description, title, author, genre, isbn, publication_year) FROM stdin;
1	2025-12-11 13:37:33.557238	\N	Simyacı	Paulo Coelho	Roman	978-975-07-2643-9	1988
\.


--
-- TOC entry 5015 (class 0 OID 24597)
-- Dependencies: 222
-- Data for Name: movies; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.movies (id, date_added, description, title, director, duration_minutes, imdb_score) FROM stdin;
1	2025-12-11 14:24:56.583543	Rüyalar içinde rüya...	Inception	Christopher Nolan	148	8.8
\.


--
-- TOC entry 5021 (class 0 OID 0)
-- Dependencies: 219
-- Name: books_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.books_id_seq', 1, true);


--
-- TOC entry 5022 (class 0 OID 0)
-- Dependencies: 221
-- Name: movies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.movies_id_seq', 1, true);


--
-- TOC entry 4862 (class 2606 OID 24595)
-- Name: books books_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT books_pkey PRIMARY KEY (id);


--
-- TOC entry 4864 (class 2606 OID 24605)
-- Name: movies movies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT movies_pkey PRIMARY KEY (id);


-- Completed on 2025-12-12 16:33:01

--
-- PostgreSQL database dump complete
--

\unrestrict MbqN0KD6WVjTDYps8aYZ8SUBplApPJcRSE2ejFXYtTYPorkEEb5s0BYnEwds7hn

